=== api-evangelist/blockchain/json-schema/com-exchange-balances-snapshot-payload-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/blockchain/refs/heads/main/json-schema/com-exchange-balances-snapshot-payload-schema.json",
  "title": "ExchangeBalancesSnapshotPayload",
  "description": "ExchangeBalancesSnapshotPayload schema from Blockchain.com WebSocket APIs",
  "type": "object",
  "properties": {
    "seqnum": {
      "type": "integer"
    },
    "event": {
      "type": "string",
      "const": "snapshot"
    },
    "channel": {
      "type": "string",
      "const": "balances"
    },
    "balances": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "currency": {
            "type": "string"
          },
          "balance": {
            "type": "number"
          },
          "available": {
            "type": "number"
          },
          "balance_local": {
            "type": "number"
          },
          "available_local": {
            "type": "number"
          },
          "rate": {
            "type": "number"
          }
        }
      }
    },
    "total_available_local": {
      "type": "number"
    },
    "total_balance_local": {
      "type": "number"
    }
  },
  "required": [
    "seqnum",
    "event",
    "channel",
    "balances"
  ]
}

=== api-evangelist/blockchain/examples/com-exchange-balances-snapshot-payload-example.json
{
  "seqnum": 1,
  "event": "snapshot",
  "channel": "balances",
  "balances": [
    {
      "currency": "BTC",
      "balance": 1.0,
      "available": 1.0,
      "balance_local": 1.0,
      "available_local": 1.0,
      "rate": 72525.0
    }
  ],
  "total_available_local": 1.0,
  "total_balance_local": 1.0
}
